#!/usr/bin/env python3
"""Generate a markdown table mapping each Java project folder to its Maven
coordinates (groupId/artifactId) and Git remote URL.

Used by the `resolve-local-maven-dependency` skill to look up which Maven
dependencies are available as local checkouts under a projects root.

Scans every immediate subdirectory of the root for a top-level pom.xml.
Folders without a pom.xml are skipped. Overwrites the output file on each run.

Usage:
    python generate-local-dependency-resolver.py
    python generate-local-dependency-resolver.py --root ~/code
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path
from typing import Optional

POM_NS = "{http://maven.apache.org/POM/4.0.0}"

SCRIPT_PATH = os.path.abspath(__file__)
SCRIPT_DIR = os.path.dirname(SCRIPT_PATH)
DEFAULT_ROOT = os.environ.get("LOCAL_DEPENDENCY_RESOLVER_ROOT") or str(Path.home() / "projects")
DEFAULT_OUTPUT = os.path.join(SCRIPT_DIR, "local-dependencies.md")


def find_child(element: ET.Element, tag: str) -> Optional[ET.Element]:
    """Find a direct child by tag, with or without the Maven POM namespace."""
    for qualified in (POM_NS + tag, tag):
        child = element.find(qualified)
        if child is not None:
            return child
    return None


def parse_pom(pom_path: str) -> Optional[dict[str, Optional[str]]]:
    """Return {groupId, artifactId, packaging} for the project at pom_path,
    inheriting groupId from <parent> when not declared on the project itself."""
    try:
        root = ET.parse(pom_path).getroot()
    except ET.ParseError:
        return None

    parent_group = None
    parent_el = find_child(root, "parent")
    if parent_el is not None:
        pg = find_child(parent_el, "groupId")
        if pg is not None and pg.text:
            parent_group = pg.text.strip()

    own_group_el = find_child(root, "groupId")
    own_group = own_group_el.text.strip() if own_group_el is not None and own_group_el.text else None

    artifact_el = find_child(root, "artifactId")
    artifact = artifact_el.text.strip() if artifact_el is not None and artifact_el.text else None

    packaging_el = find_child(root, "packaging")
    packaging = packaging_el.text.strip() if packaging_el is not None and packaging_el.text else "jar"

    return {
        "groupId": own_group or parent_group,
        "artifactId": artifact,
        "packaging": packaging,
    }


def get_git_remote(project_path: str) -> Optional[str]:
    try:
        return subprocess.check_output(
            ["git", "-C", project_path, "config", "--get", "remote.origin.url"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def collect_projects(root_dir: str) -> list[dict[str, Optional[str]]]:
    projects = []
    for entry in sorted(os.listdir(root_dir)):
        project_path = os.path.join(root_dir, entry)
        pom_path = os.path.join(project_path, "pom.xml")
        if not os.path.isfile(pom_path):
            continue
        info = parse_pom(pom_path)
        if not info or not info["artifactId"]:
            continue
        info["dir"] = entry
        info["remote"] = get_git_remote(project_path)
        projects.append(info)
    return projects


def render_markdown(projects: list[dict[str, Optional[str]]], root_dir: str) -> str:
    timestamp = datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %Z")
    lines = [
        "# Local Maven Dependencies",
        "",
        f"_Generated {timestamp} from `pom.xml` files under `{root_dir}`._",
        "",
        "> This file is auto-generated by the `resolve-local-maven-dependency` skill.",
        "> To refresh it after adding or removing projects, run:",
        "> ```",
        f"> python {SCRIPT_PATH}",
        "> ```",
        "> The script overwrites this file on each run.",
        "",
        f"Found **{len(projects)}** Java projects.",
        "",
        "| Folder | `groupId` | `artifactId` | Packaging | Git remote |",
        "|---|---|---|---|---|",
    ]
    for p in projects:
        remote = f"`{p['remote']}`" if p["remote"] else "_(no remote)_"
        lines.append(
            f"| `{p['dir']}/` "
            f"| `{p['groupId']}` "
            f"| `{p['artifactId']}` "
            f"| {p['packaging']} "
            f"| {remote} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", default=DEFAULT_ROOT, help=f"Directory to scan (default: {DEFAULT_ROOT})")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Output markdown file (overwritten each run)")
    args = parser.parse_args()

    if not os.path.isdir(args.root):
        sys.exit(
            f"error: projects root not found: {args.root}\n"
            f"Set LOCAL_DEPENDENCY_RESOLVER_ROOT or pass --root <path>."
        )

    projects = collect_projects(args.root)
    content = render_markdown(projects, args.root)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Wrote {len(projects)} projects to {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
